Dashboard.WebUI/Controllers/MasterDataController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using FrogDashboard.Authentication.MvcAttribute;
using FrogDashboard.AutoInput.AutoInput;
using FrogDashboard.Core.Enumeration;
using FrogDashboard.Core.MVCAttributes;
using FrogDashboard.Core.Utility;
using FrogDashboard.Domain.CIM;
using FrogDashboard.Domain.MasterData;
using FrogDashboard.Domain.MVCExtension;
using FrogDashboard.Domain.SysManagement;
using FrogDashboard.Interface.BaseService;
using FrogDashboard.Interface.CIM;
using FrogDashboard.Interface.MasterData.SysManagement;
using FrogDashboard.Service.Services.CIM;
using FrogDashboard.Service.Services.MasterData;
using FrogDashboard.Service.Services.MasterData.SysManagement;
using FrogDashboard.Domain.ValidationAttributes;

namespace FrogDashboard.WebUI.Controllers
{
    [CustomHandleError()]
    [CustomAuthorize()]
    public class MasterDataController : Controller
    {
        #region 实例化定义
        private ISysUser<SysUser> _sysUserService = new SysUserService();
        private ISysUserRole<SysUserRole> _sysUserRoleService = new SysUserRoleService();
        private ISysDataAuth<SysDataAuth> _sysDataAuthService = new SysDataAuthService();
        private ISysRole<SysRole> _sysRoleService = new SysRoleService();
        private ISysFunction<SysFunction> _sysFunctionService = new SysFunctionService();
        private ISysRoleFunction<SysRoleFunction> _sysRoleFunctionService = new SysRoleFunctionService();
        private ISysOrganization<SysOrganization> _SysOrgService = new SysOrgService();


        private ICimCust<CCimCust> _CimCustDBAccess = new CCimCustService();
        private IBaseService<CBasCity> _BasCityDBAccess = new CBasCityService();
        private IBaseService<CBasProvince> _BasProvinceDBAccess = new CBasProvinceService();
        private IBaseService<CBasCodeDef> _BasCodeDefDBAccessService = new CSbCodeDefService();

        //数据字典
        private IBaseService<CBasCodeType> _sysDictionaryDBAccess = new CBasCodeTypeService();
        //数据字典明细
        private IBaseService<CBasCodeDef> _sysCodeDefService = new CSbCodeDefService();

        #endregion

        #region SysFunction

        #region SysFunction
        public ActionResult SysFunction()
        {
            ViewBag.GroupItem = CUtility.ConvertEnumToDictionary(typeof(FunctionGroupType));
            ViewBag.FunctionItem = CUtility.ConvertEnumToDictionary(typeof(FuntionType));
            return View();
        }

        public JsonResult GetParentByGroupType(int groupType)
        {
            var list = _sysFunctionService.GetList().Where(s => s.FunctionType == 1 && s.Active == true && s.GroupType == groupType).ToList();
            var obj = from m in list.ToList()
                      select new
                      {
                          SysFunctionId = m.SysFunctionId,
                          FunctionName = m.FunctionName
                      };

            return Json(new { Obj = obj }, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region GetSysFunctionData
        /// <summary>
        /// 省份数据数邦定
        /// </summary>
        /// <param name="gp"></param>
        /// <param name="UserCode"></param>
        /// <param name="UserName"></param>
        /// <returns></returns>
        public JsonResult GetSysFunctionData(GridParam gp)
        {
            int pageCount, totalCount;
            Dictionary<string, string> dic = new Dictionary<string, string>();
            dic.Add("FunctionName", Request.QueryString["FunctionName"]);
            dic.Add("ControllerName", Request.QueryString["ControllerName"]);
            dic.Add("FunctionType", Request.QueryString["FunctionType"]);
            dic.Add("GroupType", Request.QueryString["GroupType"]);
            var data = _sysFunctionService.GetList(gp, dic, out pageCount, out totalCount).ToList();

            var jsonData = new
            {
                total = pageCount, //totalpages
                page = gp.page,
                records = totalCount,
                rows = (from c in data
                        let gpTypeName = GetGroupName(c.GroupType)
                        select new
                        {
                            cell = new string[] { 
                                c.SysFunctionId,
                                c.FunctionName,
                                c.ActionName,
                                c.ControllerName,
                                c.AreaName,
                                c.FunctionType.ToString(),
                                c.FunctionType==0?"<=Function>":"<=Page>",
                                c.GroupType.ToString(),
                                gpTypeName,
                                c.Active?"<=Yes>":"<=No>",
                                c.Sortid.ToString(),
                                c.Remarks,
                                c.ParentId,
                            }
                        }
                        ).ToArray()
            };
            return Json(jsonData, JsonRequestBehavior.AllowGet);
        }

        private string GetGroupName(int iGroupType)
        {
            string sGroupName = "";
            var dic = CUtility.ConvertEnumToDictionary(typeof(FunctionGroupType));
            foreach (KeyValuePair<int, string> gpType in dic)
            {
                if (gpType.Key == iGroupType)
                {
                    sGroupName = "<=" + gpType.Value + ">";
                    break;
                }
            }
            return sGroupName;
        }
        #endregion

        #region SaveSysFunction
        /// <summary>
        /// 保存省信息
        /// </summary>
        /// <param name="SysUser"></param>
        /// <returns></returns>
        public JsonResult SaveSysFunction(SysFunction sysFunction)
        {
            string str = "<=SaveSuccess>";
            if (!ModelState.IsValid)
            {
                List<string> errorList = ModelStateExtension.GetModelError(ViewData);
                str = string.Join(",", errorList.ToArray());
                return Json(new { Success = false, Msg = str }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                string errMsg;
                SysFunction tmpFunction = null;
                if (!string.IsNullOrEmpty(sysFunction.SysFunctionId))
                {
                    tmpFunction = _sysFunctionService.Get(sysFunction.SysFunctionId);
                    TryUpdateModel<SysFunction>(tmpFunction);
                }
                else
                {
                    tmpFunction = sysFunction;
                    TryUpdateModel<SysFunction>(tmpFunction);
                }

                bool Success = _sysFunctionService.Save(tmpFunction, out errMsg);
                return Json(new { Success = Success, Msg = Success ? str : errMsg }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region DeleteSysFunction
        /// <summary>
        /// 删除省信息
        /// </summary>
        /// <param name="SysUserId"></param>
        /// <returns></returns>
        public JsonResult DeleteSysFunction(string SysFunctionId)
        {
            bool success = _sysFunctionService.Delete(SysFunctionId);

            return Json(new { Success = success, Msg = success ? "<=DeleteSuccess>" : "<=DeleteFail>" },
                             JsonRequestBehavior.AllowGet);
        }
        #endregion

        #endregion

        #region SysUser

        #region SysUser
        public ActionResult SysUser()
        {
            ViewBag.LanguageItem = CUtility.ConvertEnumToDictionary(typeof(Language));
            ViewBag.teamItem = (from c in _sysCodeDefService.GetList()
                                where c.CBasCodeType.CodeType == Const.Consts.SysTeam && c.Active == true

                                select c).ToList();        

            return View();
        }

        public JsonResult GetRoleList(string userId)
        {
            if (string.IsNullOrEmpty(userId))
            {
                var list = _sysRoleService.GetList().ToList();
                var obj = from m in list.ToList()
                          select new
                          {
                              SysRoleId = m.SysRoleId,
                              RoleName = m.RoleName,
                              SysUserId = ""
                          };

                return Json(new { Obj = obj }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var list = _sysUserRoleService.GetList().Where(s => s.SysUserId == userId).ToList();
                var obj = from m in list.ToList()
                          select new
                          {
                              SysRoleId = m.SysRoleId,
                              RoleName = m.SysRole.RoleName,
                              SysUserId = m.SysUserId
                          };

                return Json(new { Obj = obj }, JsonRequestBehavior.AllowGet);
            }
        }
        #endregion

        #region GetSysUserData
        /// <summary>
        /// 省份数据数邦定
        /// </summary>
        /// <param name="gp"></param>
        /// <param name="UserCode"></param>
        /// <param name="UserName"></param>
        /// <returns></returns>
        public JsonResult GetSysUserData(GridParam gp)
        {
            int pageCount, totalCount;
            Dictionary<string, string> dic = new Dictionary<string, string>();
            dic.Add("UserCode", Request.QueryString["UserCode"]);
            dic.Add("UserName", Request.QueryString["UserName"]);
            dic.Add("Active", Request.QueryString["Active"] == null ? "1" : Request.QueryString["Active"]);

Dashboard.WebUI/Views/BasicData/BasPdcSequence.cshtml
@using FrogDashboard.Authentication.HtmlExtension;
@{
    ViewBag.Title = "<=BasPdcSequenceInfo>";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Head{
    <script type="text/javascript">

        var searchData = function () {
            var url = '@Url.Action("GetBasPdcSequence", "BasicData")';
            url += "/?" + $("#frmSearch").serialize();
            $('#tblBasPdcSequence').setGridParam({ url: url, page: 1 }).trigger("reloadGrid");
        }

        var clearForm = function () {
            $("#frmSave").find("input:text").val("");
        };

        var editData = function (result) {
            $("#tblSave").css("display", "");
            $("#btnSave").removeAttr("disabled");

            clearForm();
            $("#txtBasPdcSequenceId").val(result.BasPdcSequenceId);
            $("#txtPdc").val(result.Pdc);
            $("#txtCityCode").val(result.CityCode);
            $("#txtSequenceNumber").val(result.SequenceNumber);
            $("#cbActive").attr("checked", result.Active);
        }

        var edit = function (id) {
            var BasPdcSequenceId = $('#tblBasPdcSequence').getCell(id, 'BasPdcSequenceId');
            if (BasPdcSequenceId == "") return;
            var str = "BasPdcSequenceId=" + BasPdcSequenceId;
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetBasPdcSequenceById", "BasicData")',
                data: str,
                dataType: 'json',
                cache: false,
                success: function (result) {
                    if (result.Success) {
                        editData(result.BasPdcSequence);
                    }
                }
            });
        }

        function PageLock() {
            $("#divLock").dialog('open');
        }

        function PageUnLock() {
            $("#divLock").dialog('close');
        }
    </script>
    <script type="text/javascript">
        $(function () {
            $("#btnSave").attr("disabled", "disabled");

            $("#txtSequenceNumber").decimalInput("99");
            $("#txtPdcSearch").focus();

            $("#btnSearch").click(function () {
                clearForm();
                searchData();
                $("#tblSave").css("display", "none");
                $("#btnSave").attr("disabled", "disabled");
            });

            $("#btnAdd").click(function () {
                clearForm();
                $("#tblSave").css("display", "");
                $("#btnSave").removeAttr("disabled");
                $("#cbActive").attr("checked", true);
            });

            $("#frmSave").validate({
                rules: {
                    Pdc: {
                        required: true
                    },
                    SequenceNumber: {
                        required: true
                    }
                },
                messages: {
                    Pdc: {
                        required: "<=PdcIsRequired>"
                    },
                    SequenceNumber: {
                        required: "<=SequenceNumberIsRequired>"
                    }
                }
            });

            $("#btnSave").click(function () {
                if (!$('form[name=frmSave]').valid()) {
                    CheckFormMessage();
                    return;
                }

                //如果仓库不存在,则终止保存
                if ($("#txtCityCode").val() == "") {
                    alert("<=PlsRightPDC>");
                    return;
                }

                var str = $("#frmSave").serialize();
                str += "&Active=" + $("#cbActive").attr("checked");
                PageLock();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("SaveBasPdcSequence", "BasicData")',
                    data: str,
                    dataType: 'json',
                    cache: false,
                    success: function (result) {
                        PageUnLock();
                        alert(result.Msg);
                        if (result.Success) {
                            searchData();
                            editData(result.BasPdcSequence);
                        }
                    },
                    complete: function () {
                        PageUnLock();
                    }
                });
            });
        })
    </script>
    <script type="text/javascript" language="javascript">
        $(function () {
            $("#tblBasPdcSequence").jqGrid({
                datatype: "json",
                mtype: 'POST',
                height: 220,
                colNames: ['', '<=Pdc>', '<=SequenceNumber>', '<=CreatedUser>', '<=CreatedDate>', '<=Active>'],
                colModel: [
				{ name: 'BasPdcSequenceId', index: 'BasPdcSequenceId', hidden: true },
				{ width: 90, name: 'Pdc', index: 'Pdc' },
				{ width: 90, name: 'SequenceNumber', index: 'SequenceNumber' },
				{ width: 120, name: 'CreatedUserCode', index: 'CreatedUserCode' },
				{ width: 120, name: 'CreatedDate', index: 'CreatedDate' },
                { width: 60,name: 'Active', index: 'Active'},
                 ],
                pager: 1,
                rowNum: 15,
                sortname: 'SequenceNumber',
                sortorder: "asc",
                rownumbers: true,
                shrinkToFit: false,
                autowidth: true,
                viewrecords: true,
                sortable: true,
                width: "100%",
                pager: $('#divPager'),
                rowList: [15, 20, 50, 100],
                imgpath: '../../Content/JS/jquery.jqGrid-3.6.4/ui/images',
                ondblClickRow: function (id) {
                    edit(id);
                }
            });
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#divLock").dialog({
                autoOpen: false,
                resizable: false,
                width: 200,
                height: 110,
                modal: true,
                open: function (event, ui) {
                    $('body').css('overflow', 'hidden');
                    $('.ui-widget-overlay').css('width', '100%');
                },
                close: function (event, ui) {
                    $('body').css('overflow', 'auto');
                }
            });
        })
    </script>
    <script type="text/javascript" language="javascript">
        $(function () {
            AutoInput({
                displayFields: "PdcCode;PdcName",
                displayLabels: "<=PdcCode>;<=PdcName>",
                width: 450,
                queryFieldName: "PdcCode",
                url: '@Url.Action("GetPDCAutoInputData", "MasterData")',
                fillControls: "txtCityCode:CityCode",
                controlId: "txtPdc",
                imagePath: "../../Content/Images/AutoImage"
            });
        });
    </script>
}
<div class="column_search">
    <form id="frmSearch" name="frmSearch" action="">
    <h3 class="column_title">
        <=Search></h3>
    <table class="table">
        <tr>
            <td class="lftitle">
                <=Pdc>
                <input type="text" class="text" id="txtPdcSearch" name="Pdc" maxlength="50" />
                <input style="display: none" />
            </td>
            <td style="width:70%:">
            </td>
        </tr>
    </table>
    <div class="btn_bar">
        <div class="btn_bar">
            @Html.GenerateButton("BasicData", "GetBasPdcSequence", "btnSearch", "<=Search>")
            <input type="reset" class="button" id="btnReset" value="<=Reset>" />
        </div>
    </div>
    </form>
</div>
<div class="column_grid">
    <table id="tblBasPdcSequence">
    </table>
    <div id="divPager">
    </div>
</div>
<div class="column_edit" id="divSave">
    <form id="frmSave" name="frmSave" action="">
    <div class="btn_bar">
        @Html.GenerateButton("BasicData", "AddBasPdcSequence", "btnAdd", "<=New>")
        @Html.GenerateButton("BasicData", "SaveBasPdcSequence", "btnSave", "<=Save>")
    </div>
    <h3 class="column_title">
        <=Edit></h3>
    <table class='table' style="display: none" id="tblSave">
        <tr>
            <td class="title">
                <=Pdc>*
            </td>
            <td>
                <input type="text" class="text" id="txtPdc" name="Pdc" />
                <input type="text" class="text" id="txtCityCode" name="CityCode"
                    style="display: none" />
                <input type="text" class="text" id="txtBasPdcSequenceId" name="BasPdcSequenceId"
                    style="display: none" />
            </td>
            <td class="title">
                <=SequenceNumber>*
            </td>
            <td>
                <input type="text" class="text" id="txtSequenceNumber" name="SequenceNumber" />
            </td>
            <td class="title">
                <=Active>
            </td>
            <td>
                <input type="checkbox" id="cbActive" class="checkbox" tabindex="18" />
            </td>
            <td class="title">
            </td>
            <td>
            </td>
        </tr>
    </table>
    </form>
</div>
<div id="divLock" align="center" style="display: none" class="transparent">
    <=DataProcess><br />
    <img src="../../Content/Images/Load1.gif" />
</div>

Dashboard.WebUI/Views/BasicData/BasSpecialDay.cshtml
@using FrogDashboard.Core.Utility;
@using FrogDashboard.Authentication.HtmlExtension;
@{
    ViewBag.Title = "<=BasSpecialDayInfo>";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Head{
    <script type="text/javascript">

        var searchData = function () {
            var url = '@Url.Action("GetBasSpecialDay", "BasicData")';
            url += "/?" + $("#frmSearch").serialize();
            $('#tblBasSpecialDay').setGridParam({ url: url, page: 1 }).trigger("reloadGrid");
        }

        var clearForm = function () {
            $("#frmSave").find("input:text").val("");
            $("#frmSave").find(":checkbox").attr("checked", false);
        };

        var editData = function (result) {
            $("#tblSave").css("display", "");
            $("#btnSave").removeAttr("disabled");

            clearForm();
            $("#txtBasSpecialDayId").val(result.BasSpecialDayId);
            var date = new Date(parseInt(result.SpecialDay.replace(/\/Date\((-?\d+)\)\//, '$1')));
            $("#txtSpecialDay").val(date.format("yyyy-mm-dd"));
            $("#cbActive").attr("checked", result.Active);
            $("#txtRemark").val(result.Remark);
        }

        var edit = function (id) {
            var BasSpecialDayId = $('#tblBasSpecialDay').getCell(id, 'BasSpecialDayId');
            if (BasSpecialDayId == "") return;
            var str = "BasSpecialDayId=" + BasSpecialDayId;
            $.ajax({
                type: "POST",
                url: '@Url.Action("GetBasSpecialDayById", "BasicData")',
                data: str,
                dataType: 'json',
                cache: false,
                success: function (result) {
                    if (result.Success) {
                        editData(result.BasSpecialDay);
                    }
                }
            });
        }

        function PageLock() {
            $("#divLock").dialog('open');
        }

        function PageUnLock() {
            $("#divLock").dialog('close');
        }
    </script>
    <script type="text/javascript">
        $(function () {
            $("#btnSave").attr("disabled", "disabled");

            $("#btnSearch").click(function () {
                clearForm();
                searchData();
                $("#tblSave").css("display", "none");
                $("#btnSave").attr("disabled", "disabled");
            });

            $("#btnAdd").click(function () {
                clearForm();
                $("#tblSave").css("display", "");
                $("#btnSave").removeAttr("disabled");
                $("#cbActive").attr("checked", true);
            });

            $("#frmSave").validate({
                rules: {
                    SpecialDay: {
                        required: true
                    }
                },
                messages: {
                    SpecialDay: {
                        required: "<=SpecialDayIsRequired>"
                    }
                }
            });

            $("#btnSave").click(function () {
                if (!$('form[name=frmSave]').valid()) {
                    CheckFormMessage();
                    return;
                }
                var str = $("#frmSave").serialize();
                str += "&Active=" + $("#cbActive").attr("checked");
                PageLock();
                $.ajax({
                    type: "POST",
                    url: '@Url.Action("SaveBasSpecialDay", "BasicData")',
                    data: str,
                    dataType: 'json',
                    cache: false,
                    success: function (result) {
                        PageUnLock();
                        alert(result.Msg);
                        if (result.Success) {
                            searchData();
                            editData(result.BasSpecialDay);
                        }
                    },
                    complete: function () {
                        PageUnLock();
                    }
                });
            });
        })
    </script>
    <script type="text/javascript" language="javascript">
        $(function () {
            $("#tblBasSpecialDay").jqGrid({
                datatype: "json",
                mtype: 'POST',
                height: 220,
                colNames: ['', '<=SpecialDay>', '<=Active>', '<=CreatedUser>', '<=CreatedDate>', '<=Remark>'],
                colModel: [
				{ name: 'BasSpecialDayId', index: 'BasSpecialDayId', hidden: true },
				{ width: 120, name: 'SpecialDay', index: 'SpecialDay' },
                { width: 60, name: 'Active', index: 'Active' },
				{ width: 120, name: 'CreatedUserCode', index: 'CreatedUserCode' },
				{ width: 120, name: 'CreatedDate', index: 'CreatedDate' },
                { width: 300, name: 'Remark', index: 'Remark' }
                 ],
                pager: 1,
                rowNum: 15,
                sortname: 'SpecialDay',
                sortorder: "asc",
                rownumbers: true,
                shrinkToFit: false,
                autowidth: true,
                viewrecords: true,
                sortable: true,
                width: "100%",
                pager: $('#divPager'),
                rowList: [15, 20, 50, 100],
                imgpath: '../../Content/JS/jquery.jqGrid-3.6.4/ui/images',
                ondblClickRow: function (id) {
                    edit(id);
                }
            });
        });
    </script>
    <script type="text/javascript">
        $(function () {
            $("#divLock").dialog({
                autoOpen: false,
                resizable: false,
                width: 200,
                height: 110,
                modal: true,
                open: function (event, ui) {
                    $('body').css('overflow', 'hidden');
                    $('.ui-widget-overlay').css('width', '100%');
                },
                close: function (event, ui) {
                    $('body').css('overflow', 'auto');
                }
            });
        })
    </script>
}
<div class="column_search">
    <form id="frmSearch" name="frmSearch">
    <h3 class="column_title">
        <=Search></h3>
    <table class="table">
        <tr>
            <td class="title">
                <=SpecialDayFrom>
            </td>
            <td>
                @Html.DatePicker("SpecialDayFrom", null, new Dictionary<string, object> { { "class", "text" }, { "id", "txtSpecialDayFrom" } }, "")
                <input style="display: none" />
            </td>
            <td class="title">
                <=SpecialDayTo>
            </td>
            <td>
                @Html.DatePicker("SpecialDayTo", null, new Dictionary<string, object> { { "class", "text" }, { "id", "txtSpecialDayTo" } }, "")
            </td>
            <td class="title">
            </td>
            <td>
            </td>
            <td class="title">
            </td>
            <td>
            </td>
        </tr>
    </table>
    <div class="btn_bar">
        @Html.GenerateButton("BasicData", "GetBasSpecialDay", "btnSearch", "<=Search>")
        <input type="reset" class="button" id="btnReset" value="<=Reset>" />
    </div>
    </form>
</div>
<div class="column_grid">
    <table id="tblBasSpecialDay">
    </table>
    <div id="divPager">
    </div>
</div>
<div class="column_edit" id="divSave">
    <form id="frmSave" name="frmSave" action="">
    <div class="btn_bar">
        @Html.GenerateButton("BasicData", "AddBasSpecialDay", "btnAdd", "<=New>")
        @Html.GenerateButton("BasicData", "SaveBasSpecialDay", "btnSave", "<=Save>")
    </div>
    <h3 class="column_title">
        <=Edit></h3>
    <table class='table' style="display: none" id="tblSave">
        <tr>
            <td class="title">
                <=SpecialDay>*
            </td>
            <td>
                <input type="text" class="text" id="txtBasSpecialDayId" name="BasSpecialDayId" style="display: none" />
                @Html.DatePicker("SpecialDay", null, new Dictionary<string, object> { { "class", "text" }, { "id", "txtSpecialDay" } }, "")
            </td>
            <td class="title">
                <=Active>
            </td>
            <td>
                <input class="checkbox" type="checkbox" id="cbActive" />
            </td>
            <td class="title">
            </td>
            <td>
            </td>
            <td class="title">
            </td>
            <td>
            </td>
        </tr>
        <tr>
            <td class="title">
                <=Remark>
            </td>
            <td colspan="5">
                <input type="text" class="text" id="txtRemark" name="Remark" style="width: 94.5%"
                    maxlength="200" />
            </td>
        </tr>
    </table>
    </form>
</div>
<div id="divLock" align="center" style="display: none" class="transparent">
    <=DataProcess><br />
    <img src="../../Content/Images/Load1.gif" />
</div>